Repository nasa/prog_algs, pull requests merged in 2022-03, with the labels that each got.

#134 Implementing namedtuple syntax in prog_algs for predict and estimator
  docs/_downloads/3b9c0c03440e6a6ef2e2e2ccdbd961c5/utpredictor.py
  examples/basic_example.py
  examples/benchmarking_example.py
  examples/eol_event.py
  examples/horizon.py
  examples/playback.py
  examples/predict_specific_event.py
  examples/thrown_object_example.py
  examples/utpredictor.py
  predictor_template.py
  sphinx_config/predictors.rst
  src/prog_algs/__init__.py
  src/prog_algs/predictors/__init__.py
  src/prog_algs/predictors/monte_carlo.py
  src/prog_algs/predictors/prediction.py
  src/prog_algs/predictors/unscented_transform.py
  tests/test_predictors.py
  tutorial.ipynb
Labels: enhancement, component:State Estimators, component: Predictors

#135 Propagate prog_models array size caching throughout prog_algs
  src/prog_algs/predictors/unscented_transform.py
  src/prog_algs/state_estimators/kalman_filter.py
  src/prog_algs/state_estimators/unscented_kalman_filter.py
Labels: enhancement

#136 Set progress bar default off in MonteCarlo
  src/prog_algs/predictors/monte_carlo.py
Labels: component: Predictors

#139 Fixed behavior for new Container to support matrix logic
  src/prog_algs/state_estimators/particle_filter.py
  src/prog_algs/state_estimators/state_estimator.py
  src/prog_algs/uncertain_data/unweighted_samples.py
Labels: bug

#137 Autotesting for Jupyter notebook tutorial files
  .github/workflows/python-package.yml
  test.pkl
  tests/__init__.py
  tests/__main__.py
  tests/test_tutorials.py
Labels: enhancement

#143 fixed MC state container
  src/prog_algs/predictors/monte_carlo.py
Labels: bug

#144 Fix time alignment in prediction.
  src/prog_algs/predictors/monte_carlo.py
Labels: bug, component: Predictors

#149 Separate container for measure
  src/prog_algs/state_estimators/particle_filter.py
Labels: bug

#145 Ensure pickle-ability of classes
  src/prog_algs/state_estimators/particle_filter.py
  src/prog_algs/state_estimators/unscented_kalman_filter.py
  tests/test_metrics.py
  tests/test_predictors.py
  tests/test_uncertain_data.py
Labels: component:State Estimators, component: Predictors, component: Metrics
