Repository nasa/prog_algs, pull requests merged in 2022-05, with the labels that each got.

#174 Implementing alpha-beta plot method
  examples/playback.py
  src/prog_algs/predictors/toe_prediction_profile.py
  tests/test_predictors.py
Labels: enhancement

#173 Implementing cumulative relative accuracy for ToePredictionProfile
  src/prog_algs/metrics/__init__.py
  src/prog_algs/metrics/toe_profile_metrics.py
  src/prog_algs/predictors/toe_prediction_profile.py
  tests/test_metrics.py
Labels: enhancement, component: Metrics

#178 Implementing monotonicity for Prediction
  src/prog_algs/predictors/prediction.py
  tests/test_predictors.py
Labels: enhancement, component: Predictors

#180 Adding missing NASA copyright tags
  setup.py
  tests/test_visualize.py
  tutorial.ipynb
Labels: CI/CD

#183 Creating script to automatically check files for copyright tag
  .github/workflows/python-package.yml
  scripts/test_copyright.py
  sphinx_config/conf.py
Labels: enhancement, CI/CD

#182 Add manual testing
  tests/__init__.py
  tests/test_manual.py
Labels: enhancement, CI/CD

#184 Implement monotonicity for ToEPredictionProfile
  src/prog_algs/metrics/__init__.py
  src/prog_algs/metrics/toe_profile_metrics.py
  src/prog_algs/predictors/prediction.py
  src/prog_algs/predictors/toe_prediction_profile.py
  src/prog_algs/uncertain_data/multivariate_normal_dist.py
  src/prog_algs/uncertain_data/scalar_data.py
  src/prog_algs/uncertain_data/unweighted_samples.py
  tests/test_metrics.py
Labels: enhancement, component: Metrics

#187 Release Review Fixes
  examples/playback.py
  src/prog_algs/state_estimators/kalman_filter.py
  src/prog_algs/state_estimators/particle_filter.py
  src/prog_algs/state_estimators/state_estimator.py
  src/prog_algs/state_estimators/unscented_kalman_filter.py
Labels: documentation, CI/CD

#196 Remove unnecessary deepcopies
  src/prog_algs/predictors/monte_carlo.py
  src/prog_algs/predictors/predictor.py
  src/prog_algs/predictors/unscented_transform.py
Labels: bug

#197 Fix issue with first input being none for UTPredictor
  src/prog_algs/predictors/unscented_transform.py
Labels: bug

#198 hotfix v1.3.1
  README.md
  requirements.txt
  setup.py
  src/prog_algs/__init__.py
  src/prog_algs/predictors/monte_carlo.py
  src/prog_algs/predictors/predictor.py
  src/prog_algs/predictors/unscented_transform.py
  src/prog_algs/state_estimators/kalman_filter.py
  src/prog_algs/state_estimators/particle_filter.py
  src/prog_algs/state_estimators/state_estimator.py
  src/prog_algs/state_estimators/unscented_kalman_filter.py
  src/prog_algs/uncertain_data/multivariate_normal_dist.py
  src/prog_algs/uncertain_data/scalar_data.py
  src/prog_algs/uncertain_data/uncertain_data.py
  src/prog_algs/uncertain_data/unweighted_samples.py
  tests/test_predictors.py
  tests/test_state_estimators.py
  tutorial.ipynb
Labels: bug
